import { useState, useCallback, useEffect } from "react";
import { getScenario } from "../data/scenarios";

const SAVE_KEY = "whatif-saved-games";
const AUTOSAVE_KEY = "whatif-autosave";

export function useGameState() {
  const [currentScreen, setCurrentScreen] = useState("menu");
  const [currentScenario, setCurrentScenario] = useState(null);
  const [currentNode, setCurrentNode] = useState(null);
  const [pathHistory, setPathHistory] = useState([]);
  const [progress, setProgress] = useState(0);
  const [insight, setInsight] = useState("");
  const [isComplete, setIsComplete] = useState(false);
  const [savedGames, setSavedGames] = useState([]);

  // Load saved games on mount
  useEffect(() => {
    const saved = localStorage.getItem(SAVE_KEY);
    if (saved) {
      try {
        setSavedGames(JSON.parse(saved));
      } catch (e) {
        console.error("Error loading saved games:", e);
      }
    }
  }, []);

  // Auto-save after each action
  useEffect(() => {
    if (currentScenario && currentNode) {
      const autoSaveData = {
        scenario: currentScenario,
        currentNode,
        pathHistory,
        progress,
        timestamp: new Date().toISOString(),
      };
      localStorage.setItem(AUTOSAVE_KEY, JSON.stringify(autoSaveData));
    }
  }, [currentScenario, currentNode, pathHistory, progress]);

  const selectScenario = useCallback(scenarioId => {
    const scenario = getScenario(scenarioId);
    if (!scenario) return;

    setCurrentScenario(scenarioId);
    setCurrentNode(scenario.start);
    setPathHistory([]);
    setProgress(0);
    setInsight("");
    setIsComplete(false);
    setCurrentScreen("game");
  }, []);

  const makeChoice = useCallback(choice => {
    setPathHistory(prev => [
      ...prev,
      {
        choice: choice.text,
        outcome: choice.outcome,
        timestamp: new Date().toISOString(),
      },
    ]);

    if (choice.next) {
      setCurrentNode(choice.next);
      setProgress(prev => prev + 1);
    } else if (choice.reflection) {
      setInsight(choice.reflection);
      setIsComplete(true);
    }
  }, []);

  const resetGame = useCallback(() => {
    setCurrentScenario(null);
    setCurrentNode(null);
    setPathHistory([]);
    setProgress(0);
    setInsight("");
    setIsComplete(false);
    setCurrentScreen("menu");
  }, []);

  const saveGame = useCallback(
    saveName => {
      const scenario = getScenario(currentScenario);
      const saveData = {
        id: Date.now().toString(),
        name: saveName,
        scenario: currentScenario,
        scenarioData: scenario,
        currentNode,
        pathHistory,
        progress,
        insight,
        isComplete,
        date: new Date().toISOString(),
      };

      const updatedSavedGames = [...savedGames, saveData];
      setSavedGames(updatedSavedGames);
      localStorage.setItem(SAVE_KEY, JSON.stringify(updatedSavedGames));

      return true;
    },
    [currentScenario, currentNode, pathHistory, progress, insight, isComplete, savedGames]
  );

  const loadGame = useCallback(
    saveId => {
      const saved = savedGames.find(s => s.id === saveId);
      if (!saved) return false;

      setCurrentScenario(saved.scenario);
      setCurrentNode(saved.currentNode);
      setPathHistory(saved.pathHistory);
      setProgress(saved.progress);
      setInsight(saved.insight);
      setIsComplete(saved.isComplete);
      setCurrentScreen("game");

      return true;
    },
    [savedGames]
  );

  const deleteGame = useCallback(
    saveId => {
      const updatedSavedGames = savedGames.filter(s => s.id !== saveId);
      setSavedGames(updatedSavedGames);
      localStorage.setItem(SAVE_KEY, JSON.stringify(updatedSavedGames));
    },
    [savedGames]
  );

  const copyInsight = useCallback(() => {
    const scenario = getScenario(currentScenario);
    const insightText = `
WHAT-IF GAME INSIGHT SUMMARY
============================

Scenario: ${scenario?.title || "Unknown"}

Your Path:
${pathHistory.map((item, i) => `${i + 1}. ${item.choice}`).join("\n")}

Your Insight:
${insight}

---
Generated by What-If Game
Focus on the present. Live without regrets.
    `.trim();

    navigator.clipboard
      .writeText(insightText)
      .then(() => {
        return true;
      })
      .catch(() => {
        return false;
      });
  }, [currentScenario, pathHistory, insight]);

  return {
    currentScreen,
    currentScenario,
    currentNode,
    pathHistory,
    progress,
    insight,
    isComplete,
    savedGames,
    setCurrentScreen,
    selectScenario,
    makeChoice,
    resetGame,
    saveGame,
    loadGame,
    deleteGame,
    copyInsight,
  };
}
